// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByxnRx1OtqYDviqZ1zLL1wGli69lOE63w',
    appId: '1:980138731988:web:9ed34456e3212e80c70e41',
    messagingSenderId: '980138731988',
    projectId: 'apartman-takip-f7d9b',
    authDomain: 'apartman-takip-f7d9b.firebaseapp.com',
    storageBucket: 'apartman-takip-f7d9b.firebasestorage.app',
    measurementId: 'G-BW2FYJZXL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnc6hg5ugvVOZis26pu5DbPMP2BJTLSAA',
    appId: '1:980138731988:android:3731c5367ae98051c70e41',
    messagingSenderId: '980138731988',
    projectId: 'apartman-takip-f7d9b',
    storageBucket: 'apartman-takip-f7d9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq8plKqxETD_Pg9g0YXSPQsdp04iEgyRc',
    appId: '1:980138731988:ios:2fa6f3c8b8b7542ec70e41',
    messagingSenderId: '980138731988',
    projectId: 'apartman-takip-f7d9b',
    storageBucket: 'apartman-takip-f7d9b.firebasestorage.app',
    iosBundleId: 'com.example.apartmanTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq8plKqxETD_Pg9g0YXSPQsdp04iEgyRc',
    appId: '1:980138731988:ios:2fa6f3c8b8b7542ec70e41',
    messagingSenderId: '980138731988',
    projectId: 'apartman-takip-f7d9b',
    storageBucket: 'apartman-takip-f7d9b.firebasestorage.app',
    iosBundleId: 'com.example.apartmanTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByxnRx1OtqYDviqZ1zLL1wGli69lOE63w',
    appId: '1:980138731988:web:1416ccea10ecc294c70e41',
    messagingSenderId: '980138731988',
    projectId: 'apartman-takip-f7d9b',
    authDomain: 'apartman-takip-f7d9b.firebaseapp.com',
    storageBucket: 'apartman-takip-f7d9b.firebasestorage.app',
    measurementId: 'G-B5868PGYWE',
  );
}
